name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # To fetch all history for all branches and tags. (Will be required for caching with lerna: https://github.com/markuplint/markuplint/pull/111)

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'

      - name: Use Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Read version and commit sha
        run: |
          echo "HASH=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          echo "APP_VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV
          echo "APP_NAME=$(node -p -e "require('./package.json').name")" >> $GITHUB_ENV

      - name: Build and package
        shell: bash
        run: |
          yarn --skip-integrity-check --network-timeout 100000
          
          # make sure it builds for browser
          yarn build:browser
          
          # make sure it builds for electron
          yarn build:electron
          cd ./electron-app
          yarn
          yarn bundle
          
          # make sure it can create installer
          yarn electron-builder --linux deb
          
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9
